# Generated by Django 4.0.2 on 2022-02-09 13:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import sc_tracker.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[sc_tracker.validator.validate_nonzero_positive],
                    ),
                ),
                ("is_anon", models.BooleanField(default=False)),
                ("txn_id", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=50)),
                ("payer_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "name",
                    models.CharField(help_text="Name of the Marathon", max_length=100),
                ),
                ("slug", models.SlugField(max_length=20, unique=True)),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Donation Recipient"
                    ),
                ),
                ("recipient_paypal", models.EmailField(max_length=254)),
                (
                    "donation_minimum",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro"),
                            ("USD", "U.S. Dollar"),
                            ("SEK", "Swedish Krona"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("accept_donations", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="sc_tracker.donation",
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=1000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("READ", "Read"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sc_tracker.donor",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sc_tracker.marathon"
            ),
        ),
    ]
