# Generated by Django 4.0.2 on 2022-02-12 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('twitter_name', models.CharField(help_text='should be prefixed with an @', max_length=50)),
                ('twitch_name', models.CharField(blank=True, max_length=50)),
                ('youtube_name', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('estimate', models.DurationField()),
                ('additional_setup', models.DurationField(default=datetime.timedelta(0), help_text='will be added on top of the estimate when calculating the next run start')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sc_tracker.marathon')),
                ('runners', models.ManyToManyField(to='sc_tracker.Runner')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
